[package]
name = "disk-streaming"
version = "0.0.0"
authors = ["Matthias Geier <Matthias.Geier@gmail.com>"]
edition = "2018"

[dependencies]
errno = "*"
failure = "*"
libc = "*"
libsamplerate-sys = "*"
ogg-sys = "*"
vorbis-sys = "*"
vorbisfile-sys = "*"
